In [1]:
#Importamos numpy como np (SIEMPRE)
import numpy as np

In [3]:
lista = [0,1,2,3,4]
array_1d = np.array(lista)

#Checamos el tipo de dato de array_id
type(array_1d)
type(1.2)
#contenido del array
array_1d

array([0, 1, 2, 3, 4])

In [4]:
def multiplicar_matrices(A, B):
    # obtener dimensiones
    filas_A = len(A)
    cols_A = len(A[0])
    filas_B = len(B)
    cols_B = len(B[0])

    # checar si se pueden multiplicar A y B
    if cols_A != filas_B:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")

    # Inicializar una matriz vacía con ceros
    matriz_resultado = []
    for _ in range(filas_A):
        fila = []
        for _ in range(cols_B):
            fila.append(0)
        matriz_resultado.append(fila)

    # realizar multiplicación
    for i in range(filas_A):
        for j in range(cols_B):
            for k in range(cols_A):
                matriz_resultado[i][j] += A[i][k] * B[k][j]

    return matriz_resultado

# Ejemplo
A = [
    [1, 2, 3],
    [4, 5, 6]
]
B = [
    [7, 8],
    [9, 10],
    [11, 12]
]
C = multiplicar_matrices(A, B)
print(C)

[[58, 64], [139, 154]]


In [6]:
import random

def generar_matriz_aleatoria(N):
    matriz = []
    for i in range(N):
        fila = []
        for j in range(N):
            fila.append(random.randint(1, 9))
        matriz.append(fila)
    return matriz


N = 5
matriz_aleatoria = generar_matriz_aleatoria(N)
for fila in matriz_aleatoria:
    print(fila)

[1, 9, 3, 8, 1]
[9, 5, 8, 1, 4]
[3, 8, 5, 5, 5]
[2, 5, 1, 8, 2]
[4, 5, 3, 7, 8]


In [7]:
def imprimir_matriz(matriz):
    for fila in matriz:
        fila_formateada = ' '.join(f'{elemento:2}' for elemento in fila)
        print(fila_formateada)

In [8]:
print("Matríz de 5x5:")
m_5 = generar_matriz_aleatoria(5)
imprimir_matriz(m_5)
print("====================")
print("Matríz de 10x10:")
m_10 = generar_matriz_aleatoria(10)
imprimir_matriz(m_10)
print("====================")
print("Matríz de 20x20:")
m_20 = generar_matriz_aleatoria(20)
imprimir_matriz(m_20)
print("====================")
m_100 = generar_matriz_aleatoria(100)

Matríz de 5x5:
 1  5  4  3  5
 3  6  8  3  4
 9  2  2  5  8
 9  5  8  1  2
 1  9  7  2  4
Matríz de 10x10:
 3  7  5  3  2  4  8  8  2  6
 7  3  1  5  2  7  1  1  1  2
 7  1  6  9  1  1  4  6  8  8
 1  3  1  7  2  9  6  1  5  3
 8  4  8  5  7  7  2  1  6  6
 7  7  6  6  6  5  9  4  8  7
 3  7  3  4  4  7  9  3  2  8
 5  7  6  8  2  8  1  6  1  6
 2  2  1  2  2  1  4  8  8  7
 9  4  3  7  9  9  6  1  6  9
Matríz de 20x20:
 4  8  8  7  4  5  2  8  3  8  4  3  6  7  1  5  1  8  5  1
 4  3  5  8  7  6  2  2  3  2  9  4  2  5  6  5  4  2  6  4
 4  5  8  8  5  2  8  9  2  1  9  8  4  1  7  2  6  2  7  9
 8  3  4  4  8  9  4  4  5  3  6  6  4  9  5  1  1  4  8  4
 8  7  7  4  2  5  9  5  6  5  9  5  9  5  5  9  3  5  2  2
 5  9  9  9  9  7  1  5  2  8  2  9  9  3  3  3  4  1  4  5
 8  4  4  7  2  9  1  4  4  4  2  4  9  3  7  9  3  8  8  9
 1  2  1  1  1  5  7  2  9  5  4  9  8  8  4  4  1  7  1  6
 3  2  4  2  2  2  5  3  8  2  2  3  2  7  4  1  5  6  2  6
 7  7  2  4  1  6  9  3  3  9  8  8 

In [9]:
import time

In [10]:
start = time.time()
multiplicar_matrices(m_5, m_5)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 5x5 tardó {tiempo} seg.")

Multiplicar dos matrices de 5x5 tardó 0.0 seg.


In [11]:
start = time.time()
multiplicar_matrices(m_10, m_10)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 10x10 tardó {tiempo} seg.")

Multiplicar dos matrices de 10x10 tardó 0.0020334720611572266 seg.


In [13]:
m_1000 = generar_matriz_aleatoria(1000)
start = time.time()
multiplicar_matrices(m_1000, m_1000)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 1000x1000 tardó {tiempo} seg.")

Multiplicar dos matrices de 1000x1000 tardó 229.42434787750244 seg.


In [15]:
def generar_matriz_aleatoria_numpy(N):
    return np.random.randint(1, 10, size=(N, N))

m_1000 = generar_matriz_aleatoria_numpy(1000)

In [17]:
start = time.time()
np.dot(m_1000, m_1000)
# o bien, m_1000 @ m_1000
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 1000x1000 con Numpy tardó {tiempo} seg.")

Multiplicar dos matrices de 1000x1000 con Numpy tardó 2.0524699687957764 seg.


In [18]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr2d_f = np.array(list2, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [20]:
#convertir a enteros nuevamente
arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# convertir a enteros y luego a strings
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

In [22]:
# crear un arreglo de valroes lógicos o bools
arr2d_b = np.array([1, 0, 10, 11, 12, -1, 0], dtype='bool')
arr2d_b

array([ True, False,  True,  True,  True,  True, False])

In [23]:
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

In [24]:
lista = arr1d_obj.tolist()
lista

[1, 'a']

In [25]:
list(arr1d_obj)

[1, 'a']

In [26]:
# Crear arreglo de dos dimensiones con 3 filas y 4 columnas
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [27]:
# shape
print('Shape: ', arr2.shape)

# dtype
print('Datatype: ', arr2.dtype)

# size
print('Size: ', arr2.size)

# ndim
print('Num Dimensions: ', arr2.ndim)

Shape:  (3, 4)
Datatype:  float64
Size:  12
Num Dimensions:  2


In [28]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [29]:
arr2[1, 1]

np.float64(4.0)

In [30]:
# Extraer las primeras 3 filas y las primeras 3 columnas
arr2[:3, :3]

array([[1., 2., 3.],
       [3., 4., 5.],
       [5., 6., 7.]])

In [31]:
list2[:2, :2]   ###No se puede extraer con listas

TypeError: list indices must be integers or slices, not tuple

In [32]:
#Obtengamos el output booleano de aplicar una comparación a todo nuestro numpy array
b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
arr2[b]

array([5., 6., 5., 6., 7., 8.])

In [34]:
arr2[1,1] = np.nan  # no es un número
arr2[1,2] = np.inf  # infinito
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [36]:
valores_faltantes_bool = np.isnan(arr2) | np.isinf(arr2)

In [37]:
valores_faltantes_bool

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [38]:
arr2[valores_faltantes_bool] = -1
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [39]:
print("Hola mundo")
arr2

Hola mundo


array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [40]:
arr2
print("Media: ", arr2.mean())
print("Valor máximo: ", arr2.max())
print("Valor mínimo: ", arr2.min())

Media:  3.5833333333333335
Valor máximo:  8.0
Valor mínimo:  -1.0


In [41]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [42]:
print("Valores mínimos en columnas", np.amin(arr2, axis=0))

Valores mínimos en columnas [ 1. -1. -1.  4.]


In [43]:
print("Valores mínimos en filas: ", np.amin(arr2, axis=1))

Valores mínimos en filas:  [ 1. -1.  5.]


In [44]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [45]:
arr2_nuevo = arr2[:2,:2]  
arr2_nuevo[:1, :1] = 100  # el 100 se va a reflejar también en el array original arr2

In [46]:
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [47]:
arr2_nuevo

array([[100.,   2.],
       [  3.,  -1.]])

In [48]:
#Para evitar esto vamos a usar copy
arr2_nuevo_2 = arr2[:2, :2].copy()
arr2_nuevo_2[0, 0] = 102  # 102 no saldrá en arr2
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [49]:
arr2_nuevo_2

array([[102.,   2.],
       [  3.,  -1.]])

In [50]:
# El límite inferior es 0 por defecto
print(np.arange(5))
nuevo_arr = np.arange(10)

[0 1 2 3 4]


In [51]:
type(nuevo_arr)

numpy.ndarray

In [52]:
# 0 a 9
print(np.arange(5, 100))

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [53]:
# 0 a 9 de 2 en 2
print(np.arange(0, 100, 3.5))

[ 0.   3.5  7.  10.5 14.  17.5 21.  24.5 28.  31.5 35.  38.5 42.  45.5
 49.  52.5 56.  59.5 63.  66.5 70.  73.5 77.  80.5 84.  87.5 91.  94.5
 98. ]


In [54]:
# 10 a 1, en decrementos de 1
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


In [55]:
# Empieza en 1, terminar en 50, creando 10 números enteros
np.linspace(start=1, stop=50, num=20, dtype=int)

array([ 1,  3,  6,  8, 11, 13, 16, 19, 21, 24, 26, 29, 31, 34, 37, 39, 42,
       44, 47, 50])

In [56]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [57]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [58]:
a = [1,2,3] 

# Repetir todo el arreglo 'a' dos veces
print('Tile:   ', np.tile(a, 2))

# Repetir cada elemento de 'a' dos veces
print('Repeat: ', np.repeat(a, 4))

Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 1 1 2 2 2 2 3 3 3 3]


In [59]:
import random
random.randint(0,100)

61

In [60]:
print("Números aleatorios entre [0,1) de tamaño  2,2")
print(np.random.rand(3,5))

Números aleatorios entre [0,1) de tamaño  2,2
[[0.59225426 0.5415099  0.58097773 0.25213121 0.83746149]
 [0.10372625 0.29511366 0.89982204 0.54095349 0.28160053]
 [0.01885238 0.41371089 0.60542608 0.89682475 0.33008577]]


In [61]:
print("Números aleatorios de una distribución normal con media=0 y varianza=1 de tamaño 2,2")
print(np.random.randn(2,2))

Números aleatorios de una distribución normal con media=0 y varianza=1 de tamaño 2,2
[[ 1.66449032 -0.50430425]
 [-0.78029224 -1.19949883]]


In [62]:
print("Enteros aleatorios entre [0,10) de tamaño 2,2")
print(np.random.randint(0, 100, size=[5,5]))

Enteros aleatorios entre [0,10) de tamaño 2,2
[[ 1  8  0 97 99]
 [45 45 26 51 50]
 [18  5 39 12  1]
 [37 89 39 90 73]
 [81 36 30 95 56]]


In [63]:
print("Genera un número aleatorio entre [0,1)")
print(np.random.random())

Genera un número aleatorio entre [0,1)
0.0636809885641142


In [64]:
print("Elige 10 elementos de una lista (los resultados son equiprobables)")
print(np.random.choice(['Cara', 'Sol'], size=10))  

Elige 10 elementos de una lista (los resultados son equiprobables)
['Sol' 'Cara' 'Sol' 'Sol' 'Sol' 'Cara' 'Cara' 'Sol' 'Sol' 'Cara']


In [65]:
print("Elige 10 elementos de una lista. Cada uno con una probablidad p")
print(np.random.choice(['Cara', 'Sol'], size=10, p=[0.2, .8]))

Elige 10 elementos de una lista. Cada uno con una probablidad p
['Sol' 'Sol' 'Sol' 'Sol' 'Cara' 'Sol' 'Sol' 'Cara' 'Sol' 'Cara']


In [66]:
# ponemos una semilla 100 para reproducibilidad
np.random.seed(100)
print(np.random.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [67]:
np.random.seed(1)
arr_rand = np.random.randint(0, 10, size=100)
arr_rand

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9, 2, 4, 5, 2, 4, 2, 4, 7, 7, 9, 1, 7,
       0, 6, 9, 9, 7, 6, 9, 1, 0, 1, 8, 8, 3, 9, 8, 7, 3, 6, 5, 1, 9, 3,
       4, 8, 1, 4, 0, 3, 9, 2, 0, 4, 9, 2, 7, 7, 9, 8, 6, 9, 3, 7, 7, 4,
       5, 9, 3, 6, 8, 0, 2, 7, 7, 9, 7, 3, 0, 8, 7, 7, 1, 1, 3, 0, 8, 6,
       4, 5, 6, 2, 5, 7, 8, 4, 4, 7, 7, 4], dtype=int32)

In [68]:
vals_unicos, frecuencias = np.unique(arr_rand, return_counts=True)
print("Elementos únicos: ", vals_unicos)
print("Frecuencias      :", frecuencias)

Elementos únicos:  [0 1 2 3 4 5 6 7 8 9]
Frecuencias      : [ 9  8  7  8 11  7  8 18 10 14]


In [69]:
2**32

4294967296